language: node_js
node_js:
  - 0.10
install:
  - npm cache clean
  - make bootstrap
script:
  - make test-ci
after_success:
  - ./node_modules/.bin/lcov-result-merger "coverage/**/lcov.info" | ./node_modules/.bin/coveralls
env:
  global:
    - secure: "AfyaqEddoOzyQS2lx22xRN9OR3FN4BYLXXfISUvyJjObTD4dG08ZHydWTQcvnKMhN0V92vybt2gKOxsTXMHuy5gclMHnDLeclabgHZA6h6kOJLRyyHyj8/fDDkOAuA0dCki4/TQGENoyFl9+ei1oWvQI0ZfVCNote7zj9987gp0="
    - secure: "XBLWX9U+XotKYK5/w7DeKpaB4YtG1w3XaJH2upap+S1KgV+Nr/NHGcvHkD0ucuEkcySL6KofRXDmfyC4tNjW0jKuPs2dBxKPYL1xD0DDCYKlkX3diP9OmBAcwwqchw9U9eeN3R9UhiRCG/dnXwiuEoqy6DytbRB7UB4XSwyGQRA="
